tabs:
  - Simulation
  - Domain
  - ABL
  - Refinement
  - IO
  - Junk

frames:
  - name:  frame_time
    tab:   Simulation
    row:   0
    title: Time control

  - name:  frame_incflo
    tab:   Simulation
    row:   2
    title: Fluid and transport properties

  # ==== Domain frames ==== 
  - name:  frame_Mesh
    tab:   Domain
    #row:   0
    title: Domain and Mesh
    
  - name:  frame_BC
    tab:   Domain
    title: Boundary conditions

  - name:  frame_xBC
    tab:   Domain
    title: X Boundary conditions

  - name:  frame_yBC
    tab:   Domain
    title: Y Boundary conditions

  - name:  frame_zBC
    tab:   Domain
    title: Z Boundary conditions

  # ==== ABL frames ==== 
  - name:  frame_ABLforcing
    tab:   ABL
    row:   1
    title: ABL forcing
  - name:  frame_ABLphysics
    tab:   ABL
    title: ABL physics
  - name:  frame_ABLprop
    tab:   ABL
    title: ABL properties
  - name:  frame_Coriolis
    tab:   ABL
    title: Coriolis forces
  - name:  frame_Boussinesq
    tab:   ABL
    title: Boussinesq forces
  - name:  frame_ABLTprof
    tab:   ABL
    title: ABL temperature profiles
  - name:  frame_ABLpeturb
    tab:   ABL
    title: ABL perturbations
    

predefinedlists:
  # Check amr-wind/incflo_enums.H
  bctypes: &bctypes [pressure_inflow, pressure_outflow, mass_inflow, zero_gradient,  no_slip_wall, slip_wall, wall_model, fixed_gradient]
#[no_slip, slip_wall, wall_model ]

inputwidgets:
  # ========== Simulation inputs ==============================
  - name:       stop_time
    label:      Max time
    frame:      frame_time
    inputtype:  float
    defaultval: 100.0
    outputdef:
      AMR-Wind: time.stop_time

  - name:       max_step
    label:      Max steps
    frame:      frame_time
    inputtype:  int
    defaultval: -1
    outputdef:
      AMR-Wind: time.max_step

  - name:       fixed_dt
    label:      dt
    frame:      frame_time
    inputtype:  float
    defaultval: 0.25
    outputdef:
      AMR-Wind: time.fixed_dt

  - name:       cfl
    label:      cfl
    frame:      frame_time
    inputtype:  float
    defaultval: 0.95
    outputdef:
      AMR-Wind: time.cfl

  - name:       physics
    label:      Simulation type
    tab:        Simulation
    row:        1
    inputtype:  listbox
    optionlist: [FreeStream, ABL, RayleighTaylor, BoussinesqBubble, TaylorGreenVortex]
    defaultval: ABL
    listboxopt:
      selectmode: multiple
    outputdef:
      AMR-Wind: incflo.physics

  # ---------- incflo fluid properties ------------------------
  - name:       gravity
    label:      gravity
    frame:      frame_incflo
    inputtype:  [float, float, float]
    defaultval: [0.0, 0.0, -9.81]
    outputdef:
      AMR-Wind: incflo.gravity

  - name:       density
    label:      density
    frame:      frame_incflo
    inputtype:  float
    defaultval: 1.00
    outputdef:
      AMR-Wind: incflo.density

  - name:       viscosity
    label:      viscosity
    frame:      frame_incflo
    inputtype:  float
    defaultval: 1.872e-5
    outputdef:
      AMR-Wind: transport.viscosity

  - name:       laminar_prandtl
    label:      Laminar prandtl
    frame:      frame_incflo
    inputtype:  float
    defaultval: 0.7
    outputdef:
      AMR-Wind: transport.laminar_prandtl

  - name:       turbulent_prandtl
    label:      Turb. prandtl
    frame:      frame_incflo
    inputtype:  float
    defaultval: 0.3333
    outputdef:
      AMR-Wind: transport.turbulent_prandtl

  # ========== Mesh and Domain inputs =========================
  - name:       prob_lo
    label:      "Domain corner 1"
    frame:      frame_Mesh
    inputtype:  [float, float, float] 
    defaultval: [0.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: geometry.prob_lo

  - name:       prob_hi
    label:      "Domain corner 2"
    frame:      frame_Mesh
    inputtype:  [float, float, float] 
    defaultval: [1000.0, 1000.0, 1000.0]
    outputdef:
      AMR-Wind: geometry.prob_hi

  - name:       n_cell
    label:      "Mesh size"
    frame:      frame_Mesh
    inputtype:  [int, int, int] 
    defaultval: [48, 48, 48]
    outputdef:
      AMR-Wind: amr.n_cell

  - name:       max_level
    label:      "Max level"
    frame:      frame_Mesh
    inputtype:  int
    defaultval: 0
    outputdef:
      AMR-Wind: amr.max_level

  - name:       is_periodicx
    label:      "Periodic in X"
    frame:      frame_BC
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - frame:      frame_xBC
        activewhen: ['', 0]

  - name:       is_periodicy
    label:      "Periodic in Y"
    frame:      frame_BC
    inputtype:  bool
    defaultval: 1
    ctrlelem:
      - frame:      frame_yBC
        activewhen: ['', 0]

  - name:       is_periodicz
    label:      "Periodic in Z"
    frame:      frame_BC
    inputtype:  bool
    defaultval: 0
    ctrlelem:
      - frame:      frame_zBC
        activewhen: ['', 0]

  - name:       isperiodic
    label:    
    frame:      frame_BC
    inputtype:  mergedboollist
    mergedboollist:
      - ['is_periodicx', '1', '0']
      - ['is_periodicy', '1', '0']      
      - ['is_periodicz', '1', '0']
    outputdef:
      AMR-Wind: geometry.is_periodic

  - name:       plot_chooseview
    label:      "Choose plot view"
    tab:        Domain
    row:        6
    inputtype:  str
    optionlist: ['XY', 'XZ', 'YZ']
    defaultval: 'XY'

  - name:       xlo_type
    label:      "Lower X velocity BC"
    frame:      frame_xBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: xlo.type

  - name:       xlo_temperature_type
    label:      "Lower X temp BC"
    frame:      frame_xBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: wall_model
    outputdef:
      AMR-Wind: xlo.temperature_type

  - name:       xlo_temperature
    label:      "Lower Y temperature"
    frame:      frame_xBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: xlo.temperature

  - name:       xhi_type
    label:      "Upper X velocity BC"
    frame:      frame_xBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: xhi.type

  - name:       xhi_temperature_type
    label:      "Upper X temp BC"
    frame:      frame_xBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: fixed_gradient
    outputdef:
      AMR-Wind: xhi.temperature_type

  - name:       xhi_temperature
    label:      "Upper X temperature"
    frame:      frame_xBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: xhi.temperature

  - name:       ylo_type
    label:      "Lower Y velocity BC"
    frame:      frame_yBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: ylo.type

  - name:       ylo_temperature_type
    label:      "Lower Y temp BC"
    frame:      frame_yBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: wall_model
    outputdef:
      AMR-Wind: ylo.temperature_type

  - name:       ylo_temperature
    label:      "Lower Y temperature"
    frame:      frame_yBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: ylo.temperature

  - name:       yhi_type
    label:      "Upper Y velocity BC"
    frame:      frame_yBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: yhi.type

  - name:       yhi_temperature_type
    label:      "Upper Y temp BC"
    frame:      frame_yBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: fixed_gradient
    outputdef:
      AMR-Wind: yhi.temperature_type

  - name:       yhi_temperature
    label:      "Upper Y temperature"
    frame:      frame_yBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: yhi.temperature

  - name:       zlo_type
    label:      "Lower Z velocity BC"
    frame:      frame_zBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: zlo.type

  - name:       zlo_temperature_type
    label:      "Lower Z temp BC"
    frame:      frame_zBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: wall_model
    outputdef:
      AMR-Wind: zlo.temperature_type

  - name:       zlo_temperature
    label:      "Lower Z temperature"
    frame:      frame_zBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: zlo.temperature

  - name:       zhi_type
    label:      "Upper Z velocity BC"
    frame:      frame_zBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: no_slip_wall
    outputdef:
      AMR-Wind: zhi.type

  - name:       zhi_temperature_type
    label:      "Upper Z temp BC"
    frame:      frame_zBC
    inputtype:  str
    optionlist: *bctypes
    defaultval: fixed_gradient
    outputdef:
      AMR-Wind: zhi.temperature_type

  - name:       zhi_temperature
    label:      "Upper Z temperature"
    frame:      frame_zBC
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: zhi.temperature

  # ============================================================
  # ========== ABL forcing selection ==========================
  - name:       ABLForcing
    label:      add ABL Forcing
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlelem:  
      - frame:   frame_ABLphysics

  - name:       CoriolisForcing
    label:      add Coriolis forces
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlelem:  
      - frame:  frame_Coriolis

  - name:       BoussinesqForcing
    label:      add Boussinesq forcing
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlelem:  
      - frame:  frame_Boussinesq

  - name:       ICNS_source_terms
    label:    
    frame:      frame_ABLforcing
    inputtype:  mergedboollist
    mergedboollist:
      - ['ABLForcing',        'ABLForcing',          '']
      - ['BoussinesqForcing', 'BoussinesqBuoyancy',  '']    
      - ['CoriolisForcing',   'CoriolisForcing',     '']
    outputdef:
      AMR-Wind: ICNS.source_terms

  # ========== ABL specification ==============================
  - name:       ABL_velocity
    label:      Wind vector
    frame:      frame_ABLphysics
    inputtype:  [float, float, float] 
    defaultval: [10.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: incflo.velocity

  - name:       useWSDir
    label:      Use speed & dir instead
    frame:      frame_ABLphysics
    inputtype:  bool
    defaultval: 0
    ctrlelem:
      - input:  ABL_windspeed
      - input:  ABL_winddir
      - input:  ABL_velocity
        activewhen: ['', 0]

  - name:       ABL_windspeed
    label:      Wind speed
    frame:      frame_ABLphysics
    inputtype:  float    

  - name:       ABL_winddir
    label:      Wind direction
    frame:      frame_ABLphysics
    inputtype:  float

  - name:       forcing_height
    label:      Forcing height
    frame:      frame_ABLphysics
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: ABLForcing.abl_forcing_height

  - name:       kappa
    label:      kappa
    frame:      frame_ABLprop
    inputtype:  float
    defaultval: 0.41
    outputdef:
      AMR-Wind: ABL.kappa

  - name:       ABL_normal_direction
    label:      ABL normal direction
    frame:      frame_ABLprop
    inputtype:  int
    defaultval: 2
    outputdef:
      AMR-Wind: ABL.normal_direction

  - name:       z0
    label:      z0 roughness
    frame:      frame_ABLprop
    inputtype:  float
    defaultval: 0.0005
    outputdef:
      AMR-Wind: ABL.surface_roughness_z0

  - name:       reference_temperature
    label:      ABL ref temp
    frame:      frame_ABLprop
    inputtype:  float
    defaultval: 300.0
    outputdef:
      AMR-Wind: ABL.reference_temperature

  - name:       surface_temp_rate
    label:      surf temp rate 
    frame:      frame_ABLprop
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: ABL.surface_temp_rate

  - name:       latitude
    label:      Latitude
    frame:      frame_Coriolis
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: CoriolisForcing.latitude

  - name:       rotational_time_period
    label:      Rotation period
    frame:      frame_Coriolis
    inputtype:  float
    defaultval: 86164.0900027328
    outputdef:
      AMR-Wind: CoriolisForcing.rotational_time_period

  - name:       north_vector
    label:      North direction
    frame:      frame_Coriolis
    inputtype:  [float, float, float] 
    defaultval: [0.0, 1.0, 0.0]
    outputdef:
      AMR-Wind: CoriolisForcing.north_vector

  - name:       east_vector
    label:      East direction
    frame:      frame_Coriolis
    inputtype:  [float, float, float] 
    defaultval: [1.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: CoriolisForcing.east_vector

  - name:       boussinesq_reference_temperature
    label:      Reference Temperature
    frame:      frame_Boussinesq
    inputtype:  float
    defaultval: 300.0
    outputdef:
      AMR-Wind: BoussinesqBuoyancy.reference_temperature 

  - name:       temperature_heights
    label:      Temp profile z
    frame:      frame_ABLTprof
    inputtype:  str
    defaultval: 0.0 650.0 750.0 1000.0
    outputdef:
      AMR-Wind: ABL.temperature_heights

  - name:       temperature_values
    label:      Temp profile val
    frame:      frame_ABLTprof
    inputtype:  str
    defaultval: 300.0 300.0 308.0 308.75 
    outputdef:
      AMR-Wind: ABL.temperature_values

  - name:       perturb_velocity
    label:      Apply vel perturbations
    frame:      frame_ABLpeturb
    inputtype:  bool
    defaultval: 0
    outputdef:
      AMR-Wind: ABL.perturb_velocity
    ctrlelem:
      - input:  perturb_ref_height
      - input:  Uperiods
      - input:  Vperiods
      - input:  deltaU
      - input:  deltaV

  - name:       perturb_ref_height
    label:      Ref z for vel perturb
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 50.0
    outputdef:
      AMR-Wind: ABL.perturb_ref_height

  - name:       Uperiods
    label:      Num of periods in x
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 4.0
    outputdef:
      AMR-Wind: ABL.Uperiods

  - name:       Vperiods
    label:      Num of periods in y
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 4.0
    outputdef:
      AMR-Wind: ABL.Vperiods

  - name:       deltaU
    label:      Amp. of U fluct.
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 1.0
    outputdef:
      AMR-Wind: ABL.deltaU

  - name:       deltaV
    label:      Amp. of V fluct.
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 1.0
    outputdef:
      AMR-Wind: ABL.deltaV

  - name:       perturb_temperature
    label:      Apply T perturbations
    frame:      frame_ABLpeturb
    inputtype:  bool
    defaultval: 0
    outputdef:
      AMR-Wind: ABL.perturb_temperature
    ctrlelem:
      - input:  theta_amplitude
      - input:  cutoff_height

  - name:       theta_amplitude
    label:      Amp. of T fluct.
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 0.8
    outputdef:
      AMR-Wind: ABL.theta_amplitude

  - name:       cutoff_height
    label:      Max T perturb height
    frame:      frame_ABLpeturb
    inputtype:  float
    defaultval: 100.0
    outputdef:
      AMR-Wind: ABL.cutoff_height

  # =========== Junk stuff here ========================
  - name: input_3
    label: "list of options"
    tab:  Junk
    inputtype: str
    optionlist: ['optionA', 'optionB']
    defaultval: 'optionA'

  - name: label1
    label: "This is some label"
    labelonly: True
    tab:  Junk

  - name: label2
    label: "Some more helpful advice"
    labelonly: True
    tab:  Junk

buttons:
  - name: exitbutton
    text: Exit
    tab:  Junk
    row:  9
    command: self.quit

  - name: plotdomain
    text: Plot Domain
    row:  6
    col:  2
    tab:  Domain
    command: self.plotDomain

  - name: plotdomain
    text: Plot Domain
    tab:  ABL
    command: self.plotDomain

  - name: pullvars
    text: pull vars
    tab:  Junk
    command: "partial(pullvals, self.inputvars, statuslabel=self.statusbar)"

  - name: writeInput
    text: write input file
    tab:  Junk
    command: self.writeAMRWindInput
    #command: "partial(self.getDictFromInputs, \"AMR-Wind\")"
