tabs:
  - Simulation
  - Domain
  - ABL
  - Junk

frames:
  - name:  frame_time
    tab:   Simulation
    row:   0
    title: Time control
  - name:  frame_Mesh
    tab:   Domain
    row:   0
    title: Domain and Mesh
  - name:  frame_ABLforcing
    tab:   ABL
    row:   1
    title: ABL forcing
  - name:  frame_ABL
    tab:   ABL
    row:   2
    title: ABL physics
  - name:  frame_Coriolis
    tab:   ABL
    row:   3
    title: Coriolis forces
  - name:  frame_Boussinesq
    tab:   ABL
    row:   4
    title: Boussinesq forces

inputwidgets:
  # ========== Simulation inputs ==============================
  - name:       stop_time
    label:      Max time
    frame:      frame_time
    inputtype:  float
    defaultval: 100.0
    outputdef:
      AMR-Wind: time.stop_time

  - name:       max_step
    label:      Max steps
    frame:      frame_time
    inputtype:  int
    defaultval: -1
    outputdef:
      AMR-Wind: time.max_step

  - name:       fixed_dt
    label:      dt
    frame:      frame_time
    inputtype:  float
    defaultval: 0.25
    outputdef:
      AMR-Wind: time.fixed_dt

  - name:       cfl
    label:      cfl
    frame:      frame_time
    inputtype:  float
    defaultval: 0.95
    outputdef:
      AMR-Wind: time.cfl

  # ========== Mesh and Domain inputs =========================
  - name:       prob_lo
    label:      "Domain corner 1"
    frame:      frame_Mesh
    inputtype:  [float, float, float] 
    defaultval: [0.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: geometry.prob_lo

  - name:       prob_hi
    label:      "Domain corner 2"
    frame:      frame_Mesh
    inputtype:  [float, float, float] 
    defaultval: [1000.0, 1000.0, 1000.0]
    outputdef:
      AMR-Wind: geometry.prob_hi

  - name:       n_cell
    label:      "Mesh size"
    frame:      frame_Mesh
    inputtype:  [int, int, int] 
    defaultval: [48, 48, 48]
    outputdef:
      AMR-Wind: amr.n_cell

  - name:       plot_chooseview
    label:      "Choose plot view"
    tab:        Domain
    row:        4
    inputtype:  str
    optionlist: ['XY', 'XZ', 'YZ']
    defaultval: 'XY'

  # ============================================================
  # ========== ABL forcing selection ==========================
  - name:       ABLForcing
    label:      add ABL Forcing
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlframe:  frame_ABL

  - name:       CoriolisForcing
    label:      add Coriolis forces
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlframe:  frame_Coriolis

  - name:       BoussinesqForcing
    label:      add Boussinesq forcing
    frame:      frame_ABLforcing
    inputtype:  bool
    defaultval: 1
    ctrlframe:  frame_Boussinesq

  # ========== ABL specification ==============================
  - name:       ABL_velocity
    label:      Wind vector
    frame:      frame_ABL
    inputtype:  [float, float, float] 
    defaultval: [10.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: incflo.velocity

  - name:       forcing_height
    label:      Forcing height
    frame:      frame_ABL
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: ABLForcing.abl_forcing_height


  - name:       latitude
    label:      Latitude
    frame:      frame_Coriolis
    inputtype:  float
    defaultval: 0.0
    outputdef:
      AMR-Wind: CoriolisForcing.latitude

  - name:       rotational_time_period
    label:      Rotation period
    frame:      frame_Coriolis
    inputtype:  float
    defaultval: 86164.0900027328
    outputdef:
      AMR-Wind: CoriolisForcing.rotational_time_period

  - name:       north_vector
    label:      North direction
    frame:      frame_Coriolis
    inputtype:  [float, float, float] 
    defaultval: [0.0, 1.0, 0.0]
    outputdef:
      AMR-Wind: CoriolisForcing.north_vector

  - name:       east_vector
    label:      East direction
    frame:      frame_Coriolis
    inputtype:  [float, float, float] 
    defaultval: [1.0, 0.0, 0.0]
    outputdef:
      AMR-Wind: CoriolisForcing.east_vector

  - name:       boussinesq_reference_temperature
    label:      Reference Temperature
    frame:      frame_Boussinesq
    inputtype:  float
    defaultval: 300.0
    outputdef:
      AMR-Wind: BoussinesqBuoyancy.reference_temperature 

  # =========== Junk stuff here ========================
  - name: input_3
    label: "list of options"
    tab:  Junk
    inputtype: str
    optionlist: ['optionA', 'optionB']
    defaultval: 'optionA'

  - name: label1
    label: "This is some label"
    labelonly: True
    tab:  Junk

  - name: label2
    label: "Some more helpful advice"
    labelonly: True
    tab:  Junk

buttons:
  - name: exitbutton
    text: Exit
    tab:  Junk
    row:  9
    command: self.quit

  - name: plotdomain
    text: Plot Domain
    row:  4
    col:  2
    tab:  Domain
    command: self.plotDomain

  - name: plotdomain
    text: Plot Domain
    tab:  ABL
    command: self.plotDomain
